spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PARTICIPATEV1?useUnicode=true&characterEncoding=utf-8
    username: alokit
    password: VmAj1327

minio:
  endpoint: http://127.0.0.1:9000 
  bucketName: participate
  accessKey: minioadmin
  secretKey: minioadmin
  
redis:
  database: participate
  key:
    admin: 'admin'
    resourceList: 'resourceList'
  expire:
    common: 86400

jwt:
  tokenHeader: Authorization
  secret: participate-admin-secret
  expiration: 604800
  tokenHead: 'Bearer '
  
secure:
  ignored:
    urls:
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      
mybatis:
  mapper-locations:
  - classpath:dao/*.xml
  - classpath*:com/**/mapper/*.xml